chiwen:
  image: 10.10.1.12:5000/chiwen:latest
  options:
	- "--combo=LITE"

web:
  image: 10.10.1.12:5000/chiwen-web:master

insecure_registry:
- 10.10.1.12:5000

master:
  name: devops160
  external_ip: 10.10.1.160
  internal_ip: 172.16.88.160
  insecure_registry:
  - 10.10.1.160
  - 10.10.1.160:5000

hosts:
- name: devops161
  external_ip: 10.10.1.161
  internal_ip: 172.16.88.161
- name: devops162
  external_ip: 10.10.1.162
  internal_ip: 172.16.88.162
- name: devops163
  external_ip: 10.10.1.163
  internal_ip: 172.16.88.163
- name: devops164
  external_ip: 10.10.1.164
  internal_ip: 172.16.88.164

clusters:
- name: red
  kind: swarm
  nodes:
  - name: devops161
	  role: leader
  - name: devops162
	  role: worker
- name: blue
  kind: kubernetes
  parameters:
    network: flannel
    elastic: on
  nodes:
  - name: devops164
	  role: leader
  - name: devops165
    role: worker